#! /bin/bash

# KJV bible by defailt
BIBLE=$(dirname $0)/kjv.txt

# Show colours in terminal mode, but not in pipe mode
if tty -s 0>&1 ; then
    COLOUR="--colour=always"
    CAT=
else
    COLOUR=""
    CAT=1
fi

# Do word-wrap because less cannot
splitlines() {
    if [ "$SPLITLINES" ] ; then
        WIDTH=$( stty -a </dev/tty | grep -Po 'columns \d+' | grep -Po '\d+' )
        perl -pe '
            sub esclen($) {
                my ($str) = @_;
                $str =~ s/[\[\]]//g;
                return length($str);
            }
            $width='$WIDTH'-1;
            $decision=$width-20;
            s/(([\[\]]*.[\[\]]*){$decision,$width})( |$)/$1.(" "x($width-esclen($1)+1))/eg ;
            s/  *$//; '; 
    else
        cat
    fi
}


# 
format() {
    if [ $CAT ] ; then
        cat
    else
        # pipe the output to a browser
        WIDTH=$( stty -a </dev/tty | grep -Po 'columns \d+' | grep -Po '\d+' )

    #   # Double line spacing:
    #   sed 's/^/\n/' |
    #   fmt -s -w $WIDTH |
        $DOUBLELINE |
        sed 's/  *$//' |
        striprefs |
        splitlines |
        $ITALICS |
        grep $GREPOPTS $COLOUR "$COLOURREGEX" |
        GREP_COLORS="ms=32:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36" grep $COLOUR -P '^.*\d+:\d+|$' |
        $PAGER
    fi
}

striprefs() {
    if [ $STRIPREFS ] ; then
        sed 's/^[^:]*:[^ ]* //'
    else
        cat
    fi
}

doubleline() {
    sed 's/$/\n/'
}

italics_sed() {
  ESC=$'\e' 
  sed "s:\[:$ESC[1m:g; s:\]:$ESC[0m:g" 
}

italics_strip() {
  tr -d '[]'
}

italics_utf8() {
python <( cat << \EOF
# -*- coding: utf-8 -*-
latin = 'a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z'.split()
italic = '𝑎 𝑏 𝑐 𝑑 𝑒 𝑓 𝑔 ℎ 𝑖 𝑗 𝑘 𝑙 𝑚 𝑛 𝑜 𝑝 𝑞 𝑟 𝑠 𝑡 𝑢 𝑣 𝑤 𝑥 𝑦 𝑧 𝐴 𝐵 𝐶 𝐷 𝐸 𝐹 𝐺 𝐻 𝐼 𝐽 𝐾 𝐿 𝑀 𝑁 𝑂 𝑃 𝑄 𝑅 𝑆 𝑇 𝑈 𝑉 𝑊 𝑋 𝑌 𝑍'.split()
import sys,re
def utf_italicise(m):
  o=[]
  for c in m.group(1):
    try:
      o.append(italic[latin.index(c)])
    except:
      o.append(c)
  return ''.join(o)
brackets_re=re.compile(r'\[(.*?)\]');
for line in sys.stdin:
  sys.stdout.write(brackets_re.sub(utf_italicise,line))
EOF
)
}

###########
GREPOPTS='-Pi'
BEGIN='\b'
CONTEXT='-C 5'
SPLITLINES=
STRIPREFS=
PAGER='less -ifR'
DOUBLELINE=cat
ITALICS=italics_sed

parseopt() {
    case "$OPTIONCHAR" in
        i) BIBLE=$OPTARG ;;
        0) CONTEXT="" ;;
        [1-9]) CONTEXT="-C $OPTIONCHAR" ;;
        a) BIBLE=$(dirname $0)/af1953.txt ; SPLITLINES= ;;
        d) DOUBLELINE=doubleline ;;
        t) BIBLE=$(dirname $0)/tr1550.txt ; SPLITLINES= ; BEGIN= ;;  # UTF-8 splitting doesn't work well
        w) GREPOPTS="${GREPOPTS}w" ;;
        s) SPLITLINES=yes ;;
        r) STRIPREFS=yes ; COLOURREGEX='$' ;;
        R) STRIPVERSE=yes ; CONTEXT=""; COLOURREGEX='$' ; PAGER=cat ; COLOUR_HIGHLIGHT='' ;;
        b) MOVEREFS=yes; VERSEREF_RE='\(.*?\d+:\d+\)|$' ;;
        p) BEGIN='' ;;
        o) PAGER=cat ;;
        *)
            echo "Usage: [$0] [options] [search words] ..."
            echo ""
            echo "  -r  omit verse references"
            echo "  -R  ONLY verse references"
            echo "  -b  put the references (at the back)"
            echo "  -w  word search"
            echo "  -s  word-wrap to terminal size (automatic if output to terminal)"
            echo "  -p  partial word match (don't search word in any part of a word)"
            echo "  -0  zero verses context during search"
            echo "  -1 .. -9  more verses context"
            echo "  -t  use tr1550 greek text"
            echo "  -a  use af1953 afrikaans text"
            echo "  -o  don't pipe to less, just to stdout"
            echo "  -d  double line spacing"
            echo "  -i [file] specify input file"
            echo ""
            echo "Shows extracts having all the terms in the adjoining context"
            echo "With no options, display the text with highlighted verses using less"
            echo ""
            echo "   kjv"
            echo "   kjv liberty spy"
            echo "   kjv -t Matthew"
            exit 1
            ;;
    esac
}

while getopts "i:Rostpawrd0123456789" OPTIONCHAR ; do
    parseopt
done
shift $((OPTIND-1))

parseswitches() {
  SWITCHES="$1"
  SWITCHES="${SWITCHES:1}"
  while [ "$SWITCHES" ] ; do
    OPTIONCHAR=${SWITCHES:0:1}
    parseopt 
    SWITCHES="${SWITCHES:1}"
  done
}

####################################
COLOURREGEX='$'
if [ "$1" ] ; then
    # Late switches processing, Linux style:
    ARGS=""
    for ARG in "$@"; do
        case "$ARG" in
            -*) parseswitches "$ARG" ;;
            *) ARGS="$ARGS $ARG" ;;
        esac
    done
    EVALS=''
    for REGEX in "$@"; do
        case "$REGEX" in
          -*) true ;;
          *)
            EVALS="$EVALS | grep $GREPOPTS $CONTEXT '$BEGIN$REGEX' "
            COLOURREGEX="$BEGIN$REGEX|$COLOURREGEX"
            ;;
        esac
    done
    EVALS="tr -d $'\r' < $BIBLE $EVALS"
    eval "$EVALS" | format
elif tty -s ; then
    # Remove linefeeds and display in less
    tr -d $'\r' < $BIBLE | format
else
    # Just remove linefeeds and pipe to stdout
    tr -d '[]'$'\r' < $BIBLE
fi 

